services:
  frontend:
    build: 
      args:
        NODE_ENV: development
      context: ./frontend
    restart: unless-stopped
    ports: 
      - 5173:5173
    volumes:
      - ./frontend:/app

  backend:
    build: 
      args:
        NODE_ENV: development
      context: ./backend
    ports:
      - 3001:3001
    restart: unless-stopped
    volumes:
      - ./backend:/app

  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data
